# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1dc556dce7e651fbad90ef0fb0faa31e02c7285040f6f1905e9289abaf26cfcdcca9ce8a18ae0f454c67bd96a82de917230cc55d8e3e5077d3700fb872e4353

test:
  secret_key_base: e861a0b6653ca08cbfcbb9e9b43f375d415bd5c82f971deed75eab44eeba0512289e1504976025406db78159f585c05e4b9272b31b085847f7a16a1a25ef9afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
